---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: util-app
  template:
    metadata:
      labels:
        name: util-app
    spec:
      containers:
      - image: tsdevopsteam/platform:tp-util-app-$BUILD_NUMBER
        name: util-app
        envFrom:
        - configMapRef:
            name: utilapp-env
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ts-platform



---
apiVersion: v1
kind: Service
metadata:
  name: util-app
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    name: util-app
